### ISSUE TITLE
 Postgres Data Sources always use first defined adapter

### ISSUE THREAD

**Issue by fujit0** [public-data-space/ids-open-data-connector#1]
When adding a second Postgres adapter and defining a Data Asset using it the system will query the postgres adapter that was defined first.
Steps to reproduce: 
1. fresh open data connector environment
2. add Potgres adapter 'x' for a database running outside the scope of the docker-compose environment
3. add Data Asset 'a' using adapter 'x'
4. download ids data under Data Assets for asset 'a' works
5. add second Postgres adaper 'y' such as the example in the repository (db - ids)
6. add Data Aseet 'b' (e.g. select * from job)
7. trying to download asset 'b', the system will query the database behind adapter 'x' instead of 'y'

When creating a dummy table "job" in the database for adapter 'x' it will be delivered as a result for a download of 'b'

**Comment by vincentbohlen** [comment]
We were not able to reproduce this issue. Neither when using both out-of scope and in-scope databases, nor when using two seperate in-scope databases.
