### ISSUE TITLE
Example CKAN instance is actually not available at http://ids-backend.fokus.fraunhofer.de/api/3/action

### ISSUE THREAD

**Issue by rezacsedu** [public-data-space/ids-open-data-connector#2]
As the title says, http://ids-backend.fokus.fraunhofer.de/api/3/action is not available/accessible.

**Comment by vincentbohlen** [comment]
The Readme is a little unprecise at that point. I'll change that.

The CKAN instance is available at http://ids-backend.fokus.fraunhofer.de/

http://ids-backend.fokus.fraunhofer.de/api/3/action is the API URL that needs to be provided when registering a CKAN Data Source.

**Comment by daniel-dona** [comment]
> The CKAN instance is available at http://ids-backend.fokus.fraunhofer.de/

This doesn't work right now, 502 error.

**Comment by vincentbohlen** [comment]
The CKAN is back running. Thanks for the heads up.
