### ISSUE TITLE
DAPS Certificates

### ISSUE THREAD

**Issue by daniel-dona** [public-data-space/ids-open-data-connector#3]
The documentation states this:

> To use the broker valid DAPS certificates are necessary. The certificate needs to be placed in a keystore file. Further a truststore containing, the SSL certficate of the DAPS needs to be available. Place those files into a folder named certs located in the same folder, als the docker-compose.yml. Alternatively adjust the volume path in the docker-compose to point your keystore/truststore folder.

Could you provide some more documentation on this? We're having trouble to configure the proper certificates in order to start testing the software. 

Is it possible to use selfsigned certificates for testing purposes? 

Thank you!

**Comment by vincentbohlen** [comment]
Members of the IDSA can request a demo certificate for the DAPS implementation of Fraunhofer AISEC at https://industrialdataspace.jiveon.com/docs/DOC-2002
